### ISSUE TITLE
extensions overlap with control buttons

### ISSUE THREAD

**Issue by YoruNoKen** [datguypiko/Firefox-Mod-Blur#102]
![image](https://github.com/datguypiko/Firefox-Mod-Blur/assets/69751661/bc9e8748-b2a3-4675-b906-b900d6ae9a8b)
I'm on the latest version

**Comment by datguypiko** [comment]
Here is mine. 

What OS are you using and what other extra mods? Did you change anything in your code?

**Comment by YoruNoKen** [comment]
hi, I'm on Windows 11
no changes in the code
it's nightly

**Comment by datguypiko** [comment]
Change on line 750 to this 
```css
 #nav-bar {
    padding-right: var(--firefoxcss-control-buttons-margin) !important;
  }

```
