### ISSUE TITLE
about tab 

### ISSUE THREAD

**Issue by yiiyahui** [datguypiko/Firefox-Mod-Blur#105]
Hi, I have a question I'd like to ask.
When the number of tabs overflows, how can the width of the currently selected tab (.tabbrowser-tab[selected][fadein]:not([pinned])) be kept unchanged? If possible, how should it be done?
![Screenshot](https://github.com/datguypiko/Firefox-Mod-Blur/assets/30188835/724dc017-f0a3-4085-b42b-87ac5318aa53)

**Comment by datguypiko** [comment]
Does this do the job? Or you only need when it overflows 
https://github.com/datguypiko/Firefox-Mod-Blur/tree/master/EXTRA%20MODS/Tabs%20Bar%20Mods/Tabs%20-%20selected%20tabs%20static%20width

**Comment by datguypiko** [comment]
You can use this if you want only overflow changed
You can increase or decrease the size but both need to be the same size.
```css
#TabsToolbar #tabbrowser-tabs[overflow] .tabbrowser-tab[fadein]:not([pinned]){
   min-width: 140px !important;
} 

#TabsToolbar #tabbrowser-tabs[overflow] .tabbrowser-tab[selected][fadein]:not([pinned]) {
   min-width: 140px !important;
}
```
