### ISSUE TITLE
add container tabs color.

### ISSUE THREAD

**Issue by yiiyahui** [datguypiko/Firefox-Mod-Blur#107]
Hi,since I really like the container tabs in Firefox, I added a background color display for container tabs.I hope you like it too and consider adding it.😊
``` css
#TabsToolbar #tabbrowser-tabs .tabbrowser-tab:is([usercontextid]) .tab-background {
  background: var(--firefoxcss-tab-active-bg-color) !important;
}
#TabsToolbar #tabbrowser-tabs .tabbrowser-tab:is([usercontextid],[pinned]) .tab-background:not([selected]) {
  background: var(--identity-tab-color) !important;
  opacity: 0.2 !important;
}
``` 
Container tabs will show their default color when they are not selected.
If the code above has any errors, please fix them.thank you.
