### ISSUE TITLE
[Feature Request] Match toolbar color with current webpage

### ISSUE THREAD

**Issue by 0xCUB3** [datguypiko/Firefox-Mod-Blur#108]
Similar functionality to Safari 15+. This has been done in [this repo](https://github.com/denizjcan/Firefox-Safari-15-Theme) so I know it's possible. I'm wondering if you would be open to implementing such functionality in your project? 
Thanks :)

**Comment by datguypiko** [comment]
You will need to use the plugin https://addons.mozilla.org/en-US/firefox/addon/adaptive-tab-bar-colour/

Add this code at the end in userChrome.css

```css
/* ADAPTIVE TAB BAR COLOR */
/* Bookmarks bar background color */
#PersonalToolbar {
  background-color: var(--lwt-accent-color) !important;
}

/* Whole Main Toolbar */
#navigator-toolbox {
  background-color: var(--lwt-accent-color) !important;
}

#urlbar {
  --autocomplete-popup-highlight-background: var(
    --firefoxcss-url-autocomplete-highlight
  ) !important;
  background-color: color-mix(in srgb, currentColor 6%, transparent) !important;
  border-bottom: 1px solid #ffffff08 !important;
  border-top: 1px solid var(--lwt-accent-color) !important;
  box-shadow:none !important;
}

/* Megabar */
#urlbar[breakout][breakout-extend][open] {
  background-color: var(--toolbar-field-background-color) !important;
}

/* Styling Extra search bar that you can add to firefox */
 #search-container #searchbar {
  background-color: color-mix(in srgb, currentColor 6%, transparent) !important;
  border-bottom: 1px solid #ffffff08 !important;
  border-top: 1px solid var(--lwt-accent-color) !important;
  box-shadow:none !important;
} 

/* Normal tabs design */
.tabbrowser-tab .tab-background:not([selected]) {
  background-color:  color-mix(in srgb, currentColor 6%, transparent) !important;
}

/* Normal tabs design on hover */
#tabbrowser-tabs
  .tabbrowser-tab:hover
  > .tab-stack
  > .tab-background:not([selected]) {
  background-color: color-mix(in srgb, currentColor 14%, transparent) !important;

}

/* Selected tabs design */
#tabbrowser-tabs .tabbrowser-tab .tab-background[selected] {
  background-color: var(--tab-selected-bgcolor) !important;
}

```



And you can set the color of main page in plugin settings 
![image](https://github.com/datguypiko/Firefox-Mod-Blur/assets/61329159/d468a702-c85a-468d-9687-297ede111e7c)

and you can set the color for bright websites here 
![image](https://github.com/datguypiko/Firefox-Mod-Blur/assets/61329159/6876a8b3-588f-4950-b258-32298986fb1f)
