### ISSUE TITLE
Address bar not responsive / gets cut off on narrow window width

### ISSUE THREAD

**Issue by barjoio** [datguypiko/Firefox-Mod-Blur#11]
![image](https://user-images.githubusercontent.com/47948089/108981263-78d64100-7684-11eb-97d5-a92e8d8bc91e.png)

Just as the title and screenshot show. This is a small issue but thought it was worth letting you know anyway. This theme is really great, amazing work. Really enjoying it so far.

**Comment by fiplox** [comment]
If you add min-width to urlbar-container it get's better, but if you shink it even further it still gets cut, it's not smart but a little fix :)  
```css
	#urlbar-container {
		border-radius: 10px 10px 10px 10px !important;
		min-width: 169px !important;
	}
```
