### ISSUE TITLE
Remove folder icons from bookmars also removes favicons

### ISSUE THREAD

**Issue by Vomau** [datguypiko/Firefox-Mod-Blur#114]
remove_folder_icons_from_bookmarks.css removes website favicons too.

This worked for me and only removed the folder icon:
`#personal-bookmarks .bookmark-item[container="true"] .toolbarbutton-icon {
    display:none!important;
}`

**Comment by datguypiko** [comment]
Fixed it. 

Use this if you want folder icon if you remove the text from folders too.

```css
#PlacesToolbar .bookmark-item[container]:not([label=""]) > .toolbarbutton-icon {
    display:none !important;
}
```
