### ISSUE TITLE
Some details...

### ISSUE THREAD

**Issue by yiiyahui** [datguypiko/Firefox-Mod-Blur#116]
userChrome.css
_Hide Tab:_
![D](https://github.com/datguypiko/Firefox-Mod-Blur/assets/30188835/ea055e63-a7ce-4794-9004-b2dad288ebce)
``` css
/* ------------- Hide Tab bar with only one Tab  ----------------- */
#tabbrowser-tabs .tabbrowser-tab:only-of-type,
#tabbrowser-tabs .tabbrowser-tab:only-of-type + #tabbrowser-arrowscrollbox-periphery{
  display: none !important;
}
``` 
``` css
 /* ------------------ Downloads Panel Color-------------------- */
#downloadsPanel-mainView {
  --arrowpanel-background: var(--firefoxcss-main-bg-color) !important;
``` 
_Find bar:_
![f](https://github.com/datguypiko/Firefox-Mod-Blur/assets/30188835/03131aa0-3577-4f3e-b50b-e0f23c6130d1)
``` css
/* ------------------------- Move find bar ------------------------ */
.browserContainer > findbar {
   position: absolute;
   top: -2px;
   right: 0px;
   contain: content;
   border-radius: 0 0 var(--toolbarbutton-border-radius) var(--toolbarbutton-border-radius);
   border-top: none !important;
}
/* press ESC to exit or remove ".findbar-closebutton"*/
findbar .findbar-find-status, findbar .checkbox-check, .findbar-closebutton {
   display: none !important;
}
findbar checkbox {
   border: 1px solid var(--input-border-color);
   border-radius: var(--toolbarbutton-border-radius);
   padding: 2px 4px !important;
   margin: -2px 4px !important;
   transition: 0.1s ease-in-out;
}
findbar checkbox[checked="true"] {
   background: var(--button-active-bgcolor);
   transition: 0.1s ease-in-out;
}
``` 
_Sidebar:_
![S](https://github.com/datguypiko/Firefox-Mod-Blur/assets/30188835/ee664b87-dd8e-4de1-84cd-f337f7c07a82)
``` css
/* ------------------------- Sidebar  ----------------------------- */
#sidebar-header {border: none !important;}
search-textbox, search-box {
  appearance: none !important;
  padding: 3px;
  border: 1px solid var(--arrowpanel-border-color);
  border-radius: 4px;
  &:focus {border: 1px solid var(--firefoxcss-non-active-tabs) !important;}
}
/*Optional
#sidebar-splitter,#sidebar-close,{
  display: none !important;
} */
#viewButton {
  background-color: var(--firefoxcss-main-bg-color);
  border-radius: 4px;
  &:focus {background-color: var(--button-active-bgcolor) !important;}
}
``` 
_Fullscreen Warning:_
![ff](https://github.com/datguypiko/Firefox-Mod-Blur/assets/30188835/d8e6f477-01fe-4413-84fe-d2a5f58f18e5)
``` css
/* ------------------- Fullscreen Warning ------------------------- */
#fullscreen-warning {
  background-color: rgba(0, 0, 0, 0.5) !important;
  max-height: 48px !important;
  border: none !important;
  border-radius: 12px !important;
  box-shadow: none !important;
}
``` 
================================================================================================================================================================================
userContent.css
``` css
/* ------------------- About page color ------------------------- */
@-moz-document url-prefix("about:") {
  :root {
    --in-content-page-background: var(--firefoxcss-main-bg-color) !important;
       --in-content-box-background: var(--firefoxcss-search-bar-bg-color) !important;
       --in-content-table-background: var(--firefoxcss-search-bar-bg-color) !important;
       --newtab-primary-action-background: var(--firefoxcss-search-bar-bg-color) !important;
  }
}
``` 

I hope to improve some details for this theme

**Comment by yiiyahui** [comment]
and if set "browser.newtabpage.activity-stream.improvesearch.handoffToAwesomebar=false" in "about:config"
After:
![s](https://github.com/datguypiko/Firefox-Mod-Blur/assets/30188835/af3e54a2-3593-4f4c-8365-272648303fc1)
``` css
@-moz-document url("about:home"),url("about:newtab") {
  body {
    --newtab-background-color: var(--firefoxcss-main-bg-color) !important;
    --newtab-primary-action-background: transparent !important;
    --newtab-primary-action-background-dimmed: transparent !important;
    .search-wrapper input { 
      border-radius: 20px !important;
      background-color: var(--firefoxcss-search-bar-bg-color) !important;
      box-shadow: none !important;
      border: 1px solid var(--firefoxcss-search-text-fill) !important;
      &:focus {box-shadow: var(--firefoxcss-search-box-shadow) !important;
  }
} 
``` 	
add to userContent.css line 216
