### ISSUE TITLE
~ The work on version 3.0 ~

### ISSUE THREAD

**Issue by datguypiko** [datguypiko/Firefox-Mod-Blur#129]
Have been trying to work on it more and finish it up.
- [ ] OneLiner.
- [ ] Add responsive behavior to Oneliner for resizing.
- [ ] Extra modifications for many elements. Like changing searchbar,tabs height etc. 
- [ ] Converting the whole code to work with adding mods through about:config.
- [ ] Combine all mods into the main stuff to be togglable through about:config.
- [ ] Combine wallpaper edition to main files, automatically changes to blur when image is set.
- [ ] Create extensive list of all about:config mod preferences with previews.
- [ ] New style theme (in preview) togglable with about:config.  
- [ ] Test and add modifications for specific for linux.
- [ ] Waiting for firefox to implement vertical tabs.

Trying to make everything being changed through about:config preferences is a mess as you need to account everything working with every mod file together and not interrupting each other.

Preview:
![Screenshot 2024-06-29 013902](https://github.com/datguypiko/Firefox-Mod-Blur/assets/61329159/7b98ab77-7c67-4f7a-b5cb-cd3e79bf34f3)

![Screenshot 2024-06-29 013935](https://github.com/datguypiko/Firefox-Mod-Blur/assets/61329159/46aeb092-f403-48d2-86b0-32daa1b8f155)

![Screenshot 2024-06-29 020155](https://github.com/datguypiko/Firefox-Mod-Blur/assets/61329159/97f7d5bf-2af1-4817-8b01-abe9b1e433c9)

**Comment by Undisputed00x** [comment]
Have some suggestions/issues with the onliner titlebar, i know that its a work in progress but i post this just to make sure that you're aware of those.

* I would suggest to use a black color for selected tabs because the black color doesn't make a big contrast compared with the dark-ish grey of the rest of the tabs and titlebar but its enough to distinguish it.
<details><summary>picture</summary>
<p>

![Screenshot 2024-07-09 234834](https://github.com/datguypiko/Firefox-Mod-Blur/assets/80290008/1138cd38-c950-491a-9035-9b9f90538acf)

</p>
</details> 

* When someone uses left caption buttons layout it would be preferable to have the menu button either between the arrows or just on the right of the forward button, due to habit of have to the leftmost corner the arrow buttons like in Windows.
<details><summary>picture</summary>
<p>

![Screenshot 2024-07-09 234216](https://github.com/datguypiko/Firefox-Mod-Blur/assets/80290008/303132e4-47ec-401b-b842-ded748919d14)

</p>
</details>  

* When using MacOS caption button, the box of the buttons is non existent and have to point the cursor right above the button icons to click, this is a bit of annoying when want to make a quick click, so maybe expanding the selectable transparent buttonboxes would be ideal, here also maybe it would be good to add some gaping between the buttons.

<details><summary>picture</summary>
<p>

![Screenshot 2024-07-10 000338](https://github.com/datguypiko/Firefox-Mod-Blur/assets/80290008/196f9f0c-d0b5-49c7-8f80-5ded6446d567)
![Screenshot 2024-07-09 234454](https://github.com/datguypiko/Firefox-Mod-Blur/assets/80290008/d2c8a4bf-6fbe-45a5-bf0c-0dbf19280611)

</p>
</details> 

* A major and frustrating bug i found when using the pre-released oneliner theme version, i found that when (**using right side caption buttons**) tabs override the width of the toolbar and they're expanding underneath of the caption buttons which makes it impossible to use the last tabs due to the fact that the cursor can't hover over them.
<details><summary>picture</summary>
<p>

![Screenshot 2024-07-09 234851](https://github.com/datguypiko/Firefox-Mod-Blur/assets/80290008/abba0bb8-6a1f-4546-94ae-7b68d8e3c0b5)

</p>
</details>

**Comment by realmalikov** [comment]
Would you add these lines of code for Pocket recommendations to 3.0 by default? It's a bit unpleasant to have to do this after every update. Thank you.

```css
.sections-list .section-list {
  grid-template-columns: repeat(auto-fit, minmax(192px, 1fr)) !important;
}

.section-list .card-outer > a {
  text-decoration: none !important
}

.collapsible-section .top-sites-list {
  display: flex !important;
  justify-content: center !important;
  align-items: center !important;
  align-content: space-around !important;
  flex-direction: row !important;
  flex-wrap: wrap !important;
}

.collapsible-section .sections-list .section-list {
  justify-content: center !important;
}

.collapsible-section .section-title-container .learn-more-link-wrapper {
  display: none !important;
}
```
