### ISSUE TITLE
Bugged Icons

### ISSUE THREAD

**Issue by RustyElbow** [datguypiko/Firefox-Mod-Blur#130]
Icons in application menu are blacked out and have no spacing.

![Screenshot 2024-07-08 121128](https://github.com/datguypiko/Firefox-Mod-Blur/assets/175012016/c2ea8101-5203-4c99-bbd8-90965e5b6b74)

Thanks.

**Comment by datguypiko** [comment]
Do you have other modifications done? Remove everything except the userChrome.css and icons_in_main_menu file. 

Maybe try creating new firefox profile.
Go to about:profiles and create new profile 
![image](https://github.com/datguypiko/Firefox-Mod-Blur/assets/61329159/6f1e32b4-ac14-4155-b3cd-b9a80a7cdfa6)

Maybe you have about:config some preferences set that works against it.

**Comment by SmooQ** [comment]
> Ah yes, I have a modified user.js. Now I have to find the line thats causing the issue...

Have you found the error in your user.js? I have the same problem : /

**Comment by datguypiko** [comment]
I figured what's the issue. You downloaded the  v2.7.8_ModBlur-Firefox_v126.zip  file that doesnt have the icons in main menu fixes https://github.com/datguypiko/Firefox-Mod-Blur/commit/795497f0cbaa502fc815bb77d5c03cd63babbd52 that was added after. 

In this page https://github.com/datguypiko/Firefox-Mod-Blur/releases/tag/v2.7.8 at the top download from "Latest Full Repository"

**Comment by datguypiko** [comment]
> Brilliant! thank you. Will this update be the one with oneliner?

no, not yet but if you want to can use this for now. 

add it at the end of userChrome 

```css
/* Menu button */
#PanelUI-button {
  order: -2 !important;
}


#PanelUI-menu-button {
  padding: 0 !important;
  padding-left: 2px !important;
}

#alltabs-button {
  display: none !important;
}


:root {
  --uc-toolbar-position: 4;
}

:root {
      --firefoxcss-urlbar-min-width: 45vw;
      --firefoxcss-urlbar-max-width: 45vw;
}

#nav-bar {
    order: 1;
}
  
#titlebar {
    order: 2;
}

#PersonalToolbar {
    order: 3;
}

#TabsToolbar > .titlebar-spacer {
  display: none !important;
}


@media screen and (max-width: 1500px) {
  #urlbar-container{ 
/*     min-width: unset !important; 
    width: auto !important; 
    flex-shrink: 1 !important; */
  }
}  

   
@media (min-width: 1100px) {

  #navigator-toolbox { display: flex; flex-wrap: wrap; flex-direction: row; }

  #nav-bar {
    order: 1;
    width: var(--firefoxcss-urlbar-min-width);
/* var(--firefoxcss-control-buttons-margin); */
  }
  
  #nav-bar #urlbar-container { min-width: unset !important; width: auto !important; }

  #titlebar {
    order: 2;
    width: calc(100vw - var(--firefoxcss-urlbar-min-width) - 1px);
  }

/* --firefoxcss-control-buttons-margin */
  #PersonalToolbar {
    order: 3;
    width: 100%;

  }

  #navigator-toolbox:focus-within #nav-bar { width: var(--firefoxcss-urlbar-max-width); }
  #navigator-toolbox:focus-within #titlebar { width: calc(100vw - var(--firefoxcss-urlbar-max-width) - 1px); }
}




```
