### ISSUE TITLE
Close button

### ISSUE THREAD

**Issue by DIMFLIX-OFFICIAL** [datguypiko/Firefox-Mod-Blur#143]
How do I remove the close window button?
It is superimposed on the menu button

![image](https://github.com/user-attachments/assets/b777271d-21a1-4614-b254-43a560bf9212)

**Comment by datguypiko** [comment]
```css
#navigator-toolbox #titlebar #TabsToolbar .titlebar-buttonbox-container {
  display: none !important;
}

:root {
  --firefoxcss-control-buttons-margin: 0px !important;
}
```
