### ISSUE TITLE
[Help] move icons to the left ?

### ISSUE THREAD

**Issue by SaiyajinK** [datguypiko/Firefox-Mod-Blur#144]
hi,

I use FF v129.0.2 / FMB v2.9 and i would like to put the firefox icon on the far left and the profile icon just in his right. Is this possible ?

![image](https://github.com/user-attachments/assets/b4f438cf-9677-49f7-8cd3-0f055dc2b3d4)

thank's ✌🏻

**Comment by datguypiko** [comment]
Try adding this to userChrome.css
```css
#PanelUI-button {
  order: -2 !important;
}

#fxa-toolbar-menu-button{
  order: -1 !important;
}
```
