### ISSUE TITLE
Strange alignment of the search bar on the home page

### ISSUE THREAD

**Issue by Noktomezo** [datguypiko/Firefox-Mod-Blur#155]
The search bar is not aligned in the center when the shortcuts are disabled

![изображение](https://github.com/user-attachments/assets/a1a9f425-6815-4afa-892e-91ca344381d4)

![изображение](https://github.com/user-attachments/assets/efea88d8-e463-4c1e-a6af-9306fd2e9647)

![изображение](https://github.com/user-attachments/assets/f0f3e758-388f-4c87-91a9-8dc3108f8b03)

**Comment by datguypiko** [comment]
That's how it works by default firefox 
![{98D9F8DE-06FE-4CB2-AFEB-26D067049479}](https://github.com/user-attachments/assets/e81af8b6-a29e-4e8f-822d-bef820d13e09)

**Comment by datguypiko** [comment]
You can add this code to userContent.css file to make it centered.

Add it anywhere between line 234 and 700:
```css
.outer-wrapper.only-search {
    padding-top: 0px !important;
    align-content: center !important;
}
```
