### ISSUE TITLE
Remove tabs entirely for sidebery

### ISSUE THREAD

**Issue by unkn0wncode** [datguypiko/Firefox-Mod-Blur#170]
Hey, is there easy way to remove tabs entirely, be it horizontal of vertical, in case you just wanna use sidebery alone?

**Comment by unkn0wncode** [comment]
> I cant test it right now but you can try adding to userChrome.css
> 
> #TabsToolbar { visibility:collapse !important; }

that didn't really work, but seems if I turn on vertical and remove whole sidebar, it does the job, somewhat.
```css
#sidebar-main {
    visibility: collapse !important;
}
```
or can hide `#vertical-tabs` to leave sidebar, hard to say which is better but well, works.

Maybe for a mod would be good to make sidebar show only on hover, without tabs 🤔

**Comment by datguypiko** [comment]
Worked fine with the code I used.
![image](https://github.com/user-attachments/assets/2e8b2e3e-c680-424c-a858-958ebbdfdd55)

I dont use sidebery and firefox will implement show on hover themselves later for vertical tabs and probably the new side bar.

**Comment by Eysteinn-Orn** [comment]
> I cant test it right now but you can try adding to userChrome.css
> 
> #TabsToolbar { visibility:collapse !important; }

Hey, this actually worked for me!

I installed the theme through the easy installer fork by Alan-Kuan but adjusted the `hide_tab_bar.css` file to include your modification since I am using sideberry like so.
```css
/* Hide Tab Bar */

#TabsToolbar {
  visibility:collapse !important;
  }
  
#titlebar {
  visibility: collapse !important;
}
```
![image](https://github.com/user-attachments/assets/fa49acdd-da88-4281-9840-5d19639000ef)
