### ISSUE TITLE
What are the lines for the border under the tabbar, bookmarks, urlbar, etc.?

### ISSUE THREAD

**Issue by superdragon1772** [datguypiko/Firefox-Mod-Blur#177]
I would like to have a border under the tabbar, bookmarks, urlbar, etc. I may have messed with it before, but I'm looking for the pros who knows their code because I'm too lazy.

![Image](https://github.com/user-attachments/assets/624d36e0-90ac-4067-a47b-ac3c9f986482)

I did try, here is an example. I put in and replaced code over and over, but I can't find it. For such a small thing I can't bother going through it all. Hoping you can help me whoever is reading this.

![Image](https://github.com/user-attachments/assets/319a24ce-4a46-49a8-9b27-8aeec532c578)

Or if there is a better method than finagling with the numbers or somethin. Thanks.

**Comment by alnviana** [comment]
I know it is a little late, but...
You can do that using the [Browser Toolbox](https://firefox-source-docs.mozilla.org/devtools-user/browser_toolbox/index.html). It let's you use the Inspector from the Web Developer Tools withe the Firefox's interface elements, as like you usually can do with any HTML page.

**Comment by superdragon1772** [comment]
Still can't find it, but this helps out a lot. Thank you!

**Comment by alnviana** [comment]
In theory, you just have to use one of those:
```css
#navigator-toolbox {
    border-bottom: 2px solid red !important;
}
#TabsToolbar {
    border-bottom: 2px solid limegreen !important;
}
#PersonalToolbar {
    border-bottom: 2px solid blue !important;
}
#browser {
    border-top: 2px solid fuchsia !important;
}
```
The option that seems to be the right one is the #navigator-toolbox, but for some reason it doesn't work.
The #browser works, but seems to not be the right way to do...
The #TabsToolbar and #PersonalToolbar could be used, but you have to make one or the other activate only when the bookmark bar is enable or not.

I hope you now achieve your goal. :)
