### ISSUE TITLE
Centered Tabs

### ISSUE THREAD

**Issue by abusoww** [datguypiko/Firefox-Mod-Blur#192]
![Image](https://github.com/user-attachments/assets/456aff43-0bc0-437e-810f-6797f22a0004)

I think you should add mod to centered tabs 

`#tabbrowser-arrowscrollbox:not([overflowing]) {
  --uc-justify-content: center;
}

scrollbox[orient="horizontal"] > slot {
  justify-content: var(--uc-justify-content, initial);
}`

**Comment by FuglyShmugly** [comment]
Sorry for going off topic. Do you know how to center suggestions dropdown when you type in the address bar? I can't figure it out they just keep being glued to the left side.

**Comment by datguypiko** [comment]
> Sorry for going off topic. Do you know how to center suggestions dropdown when you type in the address bar? I can't figure it out they just keep being glued to the left side.

try this

```css
.urlbarView-row-inner{ justify-content: center !important; }
.urlbarView-url{ flex-grow: 0 !important; }

```
