### ISSUE TITLE
Close button doesn't get focus if you hover the exact corner (or right side) of the screen.

### ISSUE THREAD

**Issue by FuglyShmugly** [datguypiko/Firefox-Mod-Blur#201]
It's a bit annoying if you got used to dragging mouse to top right to close windows.

To fix this I added:

```CSS
#navigator-toolbox
  {
    margin-top: -5px !important;
    margin-right: -4px !important;
  }
```

-5 and -4 works, if you go higher the issue comes back.
