### ISSUE TITLE
differentiate unloaded tabs from loaded ones

### ISSUE THREAD

**Issue by FawazTakahji** [datguypiko/Firefox-Mod-Blur#202]
this can be done by enabling browser.tabs.fadeOutUnloadedTabs in config, this is how im doing it but im not very good at designing stuff so it doesn't look that good, and the text is kind of hard to read
```css
.tabbrowser-tab[pending] {
  opacity: 0.5 !important;
}
```

![Image](https://github.com/user-attachments/assets/b06e8bcb-aa3a-42b8-b7a1-80d4bf6baf21)
