### ISSUE TITLE
Duplicate Minimize, Maximize and Close buttons.

### ISSUE THREAD

**Issue by kubakakauko** [datguypiko/Firefox-Mod-Blur#32]
Is there a way to remove the duplicate the browser close buttons.
 That's how it looks like.

![Image](https://i.imgur.com/zhv9CA8.png)

This is my folder structure
![image](https://i.imgur.com/jeMHzX7.png)

**Comment by kubakakauko** [comment]
Its something to do with acrylic_micaforeveryone.css and userChrome.css but I don't know how to fix it.

**Comment by datguypiko** [comment]
It is mica problem. It creates another set of button which you cant disable, move or hide nor interact. What I do is put the old ones in the same place and just hide with opacity.

So the issue seems happening because of scaling in your windows, or resolution for the positioning.


For now you can hide the normal buttons open the  acrylic_micaforeveryone.css  file 

remove these lines (around 170)

```css
#navigator-toolbox:not(:-moz-window-inactive):-moz-lwtheme #navigator-toolbox .titlebar-button:not(.titlebar-close),
#navigator-toolbox:not(:-moz-window-inactive):-moz-lwtheme #navigator-toolbox .titlebar-close:not(:hover)
{
   list-style-image: none !important;
}
```

and add this 

```css
#navigator-toolbox .titlebar-button:not(.titlebar-close),
#navigator-toolbox .titlebar-close:not(:hover) {
	list-style-image: none !important;
}
```

It will fix it. But the close button on hover will have a little bit of wrong positioning.
Will try look into if there is anyway to fix this.

**Comment by datguypiko** [comment]
I will try hiding the close button too and adjust the background  color  when hovering so you can see the button without it changing position. Will post the code here and update the main files.

**Comment by kubakakauko** [comment]
Thank you, that worked well!

Im not sure if its in any way useful to anyone nor if its a good practice but i've changed 
```css
#TabsToolbar .titlebar-buttonbox-container .titlebar-button > .toolbarbutton-icon {
  height: 12px !important;
  min-height: 12px !important;
  width: 12px !important;
  min-width: 12px !important;
}
```
to this 
```css
#TabsToolbar .titlebar-buttonbox-container .titlebar-button > .toolbarbutton-icon {
  margin-top: 4px !important;
  height: 12px !important;
  min-height: 12px !important;
  width: 12px !important;
  min-width: 12px !important;
}
```
for some reason it stopped the window close button from jumping when hovered over.
