### ISSUE TITLE
Glitchy tab close animation

### ISSUE THREAD

**Issue by he2a** [datguypiko/Firefox-Mod-Blur#33]
Just installed this great theme, but theres only one problem. If I open multiple tabs and then close some from beginning, the rest of the tabs and the new tab button moves very slowly to required position.

https://user-images.githubusercontent.com/21215870/204345605-306111d4-a92c-4e0f-930a-14d4d1ccb522.mp4

I've been using the following mods for the theme.
![Screenshot 2022-11-28 232255](https://user-images.githubusercontent.com/21215870/204346804-899ed7fc-9b29-45df-807e-b1065d0401a8.png)

**Comment by datguypiko** [comment]
I cant reproduce it. It closes instantly for me. 
Try just using only userChrome.css and userContent.css, image folder  in chrome directory.

**Comment by datguypiko** [comment]
The issue is Nightly Firefox, the stable build doesn't have it. Will try check what could be causing it for that version.

**Comment by datguypiko** [comment]
I found the problem but need to test more why it's happening.

For now fix is:

In userChrome.css remove 
` transition: color 250ms ease !important;`
from:
```css
/* ======================== Tabs ======================================= */
/* ----- Non active tabs have darker text ----- */
.tabbrowser-tab:not([visuallyselected="true"]):not([multiselected]):not(:hover) {
  color: hsla(0, 0%, 100%, 0.65) !important;
  transition: color 250ms ease !important;  /* remove this */
}
```

let me know if this works.
