### ISSUE TITLE
Non active tabs have darker text, but with Light theme?

### ISSUE THREAD

**Issue by yokoffing** [datguypiko/Firefox-Mod-Blur#34]
I have an app that switches my programs from Light theme to Dark theme at a certain time everyday, and I enjoy using your code for:

```
/* ----- Non active tabs have darker text ----- */

.tabbrowser-tab:not([visuallyselected="true"]):not([multiselected]):not(:hover) .tab-label-container 
.tab-label {
  color: hsla(0, 0%, 100%, 0.65) !important;
}

.tabbrowser-tab .tab-label-container 
.tab-label {
  transition: color 250ms ease !important;
}
```

But, this makes text unreadable in light mode. Do you know what I should add to make this flexible between light and dark theme?

**Comment by datguypiko** [comment]
How does it look when it set to light and what program is that?

One thing you could try using are these
`@media (prefers-color-scheme: dark) {  }`

`@media (prefers-color-scheme: light) {  }`

**Comment by yokoffing** [comment]
Firefox Nightly 

![light](https://user-images.githubusercontent.com/11689349/205084298-70857aac-6145-4da4-afdb-0321c1120040.png)

**Comment by datguypiko** [comment]
Try this 

```css

@media (prefers-color-scheme: light) { 
  .tabbrowser-tab:not([visuallyselected="true"]):not([multiselected]):not(:hover) .tab-label-container 
  .tab-label {
    color: black !important;
  }

  .tabbrowser-tab .tab-label-container 
  .tab-label {
    color: black !important;
  }
}

```
