### ISSUE TITLE
Tab's close button on the left

### ISSUE THREAD

**Issue by stpnwf** [datguypiko/Firefox-Mod-Blur#39]
I like to use the titlebars on the left, like on macOS. Is it possible to get an option for the tab's close button to also show up on the left for extra consistency in those situations?

Currently they show up on the right regardless, as briefly seen here:

![titlebars](https://i.imgur.com/cvBzN61.gif)

**Comment by datguypiko** [comment]
Add to the end of userChrome.css. ([source](https://mrotherguy.github.io/firefox-csshacks/?file=combined_favicon_and_tab_close_button.css))
```css

.tab-content{
  pointer-events: none
}
.tab-icon-image:not([busy]){ display: block !important; }
:where(.tab-content:hover) .tab-icon-image,
:where(.tab-content:hover) > .tab-icon-stack{
  visibility: hidden;
}
.tab-close-button{
  -moz-box-ordinal-group: 0;
  display: -moz-box !important;
  position: relative;
  margin-inline: -4px -20px !important;
  padding-inline-start: 7px !important;
  opacity: 0;
  width: unset !important;
  pointer-events: auto;
}
.tab-close-button:hover{ opacity: 1 }
.tabbrowser-tab[pinned] .tab-close-button{ display: none !important; }
```
