### ISSUE TITLE
Enhanced Tracking Protection icon missing on search bar

### ISSUE THREAD

**Issue by Fre148** [datguypiko/Firefox-Mod-Blur#43]
The icon to change the settings like enabled, disabled, strict, etc. is missing.

Help please! Thank you for your work :D

**Comment by datguypiko** [comment]
It's removed intentionally because you can set it in settings. Remove this code at around line 762 in userChrome.css

```css
#tracking-protection-icon-container {
  display: none !important;
}
```
