### ISSUE TITLE
Librewolf home tab icon missing / Librewolf icons and branding

### ISSUE THREAD

**Issue by TK-NC** [datguypiko/Firefox-Mod-Blur#46]
Hello!

Beeen using this theme with Librewolf for a while and I'm having an issue with the icons in the home pages.

Here's what the home page should look like:
![image](https://user-images.githubusercontent.com/70816294/222915174-3733f644-18c3-47ef-9806-1af73c14234e.png)

Here's what it looks like with Librewolf (missing the firefox logo):
![librewolf 04 de março de 2023 (12-43-37 PM) 1920x1040](https://user-images.githubusercontent.com/70816294/222915422-e5e3f6a2-41e4-4908-a618-c48db714e1f7.png)
![librewolf 04 de março de 2023 (12-44-18 PM) 1920x1040](https://user-images.githubusercontent.com/70816294/222915449-b0ae19c1-c315-47cf-a01d-2e07a6da8a86.png)

Feel free to close this issue if you don't want to offer Librewolf support. This issue is mainly about the home tab logo, but if you're interested the Librewolf branding can be found here (that's what I used to make the icon in the upper left corner): https://gitlab.com/librewolf-community/branding

**Comment by datguypiko** [comment]
Download these 4 images from [here](https://github.com/datguypiko/Firefox-Mod-Blur/tree/master/old/LibreWolf) and put it inside `/image/` folder.

</br>

Open userContent.css file and change these:

1. Add this code around line `120` below "body {...}"

```css
.search-wrapper .logo-and-wordmark .wordmark {
    background: url("image/Logo.png") no-repeat center center !important;
}
.search-wrapper .logo-and-wordmark .logo {
    background: url("image/icon_transparent.svg")  no-repeat center !important;
}
```

2. And for private page (you can change -25px value for the distance from the search box)

```css
CHANGE THIS CODE AROUND LINE 34

#about-private-browsing-logo.logo {
    background-image: url("image/about-logo-private-changed.png") !important;
    opacity: 0.9 !important;
}

CHANGE TO ---->

#about-private-browsing-logo.logo {
    background-image: url("image/icon_transparent_private.svg") !important;
    opacity: 0.9 !important; 
}
.logo-and-wordmark .wordmark {
    background: url("image/Logo_Private.png") no-repeat center center !important;
    background-size: 172px !important;
}
.logo-and-wordmark {margin-bottom: -25px !important;}
```

![image](https://user-images.githubusercontent.com/61329159/222956613-40a2b28b-06a9-4531-ad64-8c6b75eb422f.png)
![image](https://user-images.githubusercontent.com/61329159/222956623-2f32d0c7-676b-4085-a896-e250b08b6832.png)
