### ISSUE TITLE
Weird Extension icon location

### ISSUE THREAD

**Issue by reihanboo** [datguypiko/Firefox-Mod-Blur#51]
The image below is what my browser looks like. The Extension icon is supposed to be on the right side.

![image](https://user-images.githubusercontent.com/85765686/225509068-41c07120-8a02-422b-9f70-0faac71cfaa5.png)

I cannot move the icon by just dragging it on Customize Taskbar because in there, it shows the Extension icon being on the right. https://i.imgur.com/h7I5HhZ.png

Any fixes?

**Comment by datguypiko** [comment]
You cant move that button, it's locked in place by firefox. It's on the right side in customization view because I didnt bother moving it.

**Comment by datguypiko** [comment]
You can move the extension button to the right side by removing this code from "min-max-close_buttons.css" file:

```css
toolbar:not([customizing]) > #nav-bar-customization-target {
  -moz-box-ordinal-group: 2 !important;
}
```

or remove this whole thing if you want all buttons on the right side:
![image](https://user-images.githubusercontent.com/61329159/225751330-49a42dfc-97c1-4b0d-827a-5057acde4e02.png)
