### ISSUE TITLE
Tabbar under search bar

### ISSUE THREAD

**Issue by TaouMou** [datguypiko/Firefox-Mod-Blur#54]
Hello, first of all, thank you so much, because this theme is the best I've seen.

As for my issue, I find it weird because I've checked other issues and couldn't find someone with the same layout. I couldn't find how to change it do it in the userChrome.css.

**Issue:** I want to make the search bar with the corresponding buttons on top of the tabbar, is it possible?

![image](https://user-images.githubusercontent.com/94767268/227996872-00743fd4-76ce-4821-a0e3-559d1e5bc6ff.png)

![image](https://user-images.githubusercontent.com/94767268/227996947-c1b7f918-2e7c-48a3-b1cb-dc9c25838074.png)

**Comment by datguypiko** [comment]
Just remove this section in userchrome, should be enough

```css
/* ----------------------------------------------------------------- */
/* ------------------ close/min/max buttons ------------------------ */
/* ----------------------------------------------------------------- */

/* ----- Close/min/max fix ----- */
#toolbar-menubar .titlebar-button {
  padding-block: 0px !important;
}

#TabsToolbar .titlebar-buttonbox-container {
  -moz-box-ordinal-group: 0 !important;
  padding-top: 5px !important;
  padding-bottom: 5px !important;
  padding-right: 3px !important;
  padding-left: 3px !important;
}

#nav-bar {
  padding-left: 118px;
}

#navigator-toolbox:not([inFullscreen])
  #TabsToolbar
  .titlebar-buttonbox-container {
  visibility: visible !important;
  display: block !important;
  position: absolute !important;
  top: 1px;
  left: 0;
}

#TabsToolbar .titlebar-buttonbox-container .titlebar-button {
  border-radius: var(--toolbarbutton-border-radius);
}

.titlebar-buttonbox-container .titlebar-button > .toolbarbutton-icon {
  height: 12px !important;
  min-height: 12px !important;
  width: 12px !important;
  min-width: 12px !important;
}

.titlebar-buttonbox-container .titlebar-button {
  padding: 8px !important;
  padding-left: 10px !important;
  padding-right: 10px !important;
  margin-left: 2px !important;
  margin-right: 2px !important;
}

:root[sizemode="maximized"] .titlebar-buttonbox-container {
  padding-top: 0px !important;
}

.titlebar-buttonbox-container .titlebar-min {
  -moz-box-ordinal-group: 2 !important;
}

.titlebar-buttonbox-container .titlebar-max,
.titlebar-restore {
  -moz-box-ordinal-group: 1 !important;
}

.titlebar-buttonbox-container .titlebar-close {
  -moz-box-ordinal-group: 0 !important;
}

@media only screen and (max-width: 670px) {
  #navigator-toolbox:not([inFullscreen])
    #TabsToolbar
    .titlebar-buttonbox-container {
    visibility: visible !important;
    display: block !important;
    position: relative !important;
  }

  #navigator-toolbox:not([inFullscreen]) #nav-bar {
    padding-left: initial !important;
  }
}
```
