### ISSUE TITLE
How to remove the symbols ('x','-',...) from the min, max, close buttons?

### ISSUE THREAD

**Issue by khezu01** [datguypiko/Firefox-Mod-Blur#59]
I wanted it to be light gray and when hovered, there's only the colors and no opacity changes. I tried on my own, but the buttons seem to move upwards slightly when hovered. It was easier with the svgs before lol.

**Comment by datguypiko** [comment]
Just change the opacity to 0.

```css
 #TabsToolbar .titlebar-buttonbox-container .titlebar-restore:hover::before,
  #TabsToolbar .titlebar-buttonbox-container .titlebar-restore:hover::after {
	opacity: 0;
	top: 50%;
  }
```

```css
 #TabsToolbar .titlebar-buttonbox-container .titlebar-close:hover::before,
  #TabsToolbar .titlebar-buttonbox-container .titlebar-close:hover::after {
	opacity: 0;
	top: 50%;
  }
```

```css
  #TabsToolbar .titlebar-buttonbox-container .titlebar-max:hover::before,
  #TabsToolbar .titlebar-buttonbox-container .titlebar-max:hover::after {
	opacity: 0;
	top: 50%;
  }
```


```css
 #TabsToolbar .titlebar-buttonbox-container .titlebar-min:hover::before {
	opacity: 0;
	top: 50%;
  }
```
