### ISSUE TITLE
[Linux, GNOME, GTK] System window titlebar buttons broken

### ISSUE THREAD

**Issue by jdev082** [datguypiko/Firefox-Mod-Blur#60]
When I use the left system titlebar icons, the buttons are usable but the icons do not appear. When I use the right system titlebar icons, the menu, bookmark, and extension buttons are under the buttons with no icon and prevent the menu, bookmark, and extension buttons from working.

**Comment by jdev082** [comment]
Screenshot (left system titlebar buttons):
![image](https://github.com/datguypiko/Firefox-Mod-Blur/assets/92550746/7cb65039-b264-4954-908a-c854c682d40a)

**Comment by datguypiko** [comment]
So there is few things or ways to do it:
 
### **1. Disable dark theme and add this code to userChrome.css**  ###
![image](https://github.com/datguypiko/Firefox-Mod-Blur/assets/61329159/29eb020c-956c-4be1-ba2a-1947fa348dd6)

Change padding-right to padding-left if on the left side. Select size you need. 
```css
#nav-bar {
  padding-right: 30px !important;
}
```
This line is to move the button down a bit if it's not centered.
```css
#TabsToolbar .titlebar-buttonbox-container {
  padding-top: 5px !important;
}
```

### **2. Other way is to use my custom[ macos buttons,](https://github.com/datguypiko/Firefox-Mod-Blur/tree/master/EXTRA%20MODS/Min-max-close%20window%20buttons) they work fine. Just needs lowering padding because some distros only have one button**  ###

lower from 90px to what fits you. 
```css
#nav-bar {
  padding-left: 90px !important;
  padding-right: initial !important;
}
```
![image](https://github.com/datguypiko/Firefox-Mod-Blur/assets/61329159/2c82d8ad-8f6b-4ab8-a61a-c2a5b6b7b96a)

### **3. I haven't gotten to fixing the buttons for linux but I was going to soon. **  ###
