### ISSUE TITLE
Text color is not readable (not white)

### ISSUE THREAD

**Issue by aahajj** [datguypiko/Firefox-Mod-Blur#62]
I had this issue where text in the urlbar, in the main menu and in the more tools section is not readable. 
![image](https://github.com/datguypiko/Firefox-Mod-Blur/assets/126328773/6f9b9566-1570-4e35-9a45-8fde937f06a3)
For the Urlbar I added this in #urlbar
```css
#urlbar {
  --urlbar-toolbar-height: 38px !important;
    color: white !important;
}
```
which fixed it. Can you please tell me where to fix the other?

I am using Mozilla Firefox 113.0.2
