### ISSUE TITLE
Youtube bug

### ISSUE THREAD

**Issue by devenrgy** [datguypiko/Firefox-Mod-Blur#70]
When you search for something on youtube and then erase the word, you get this bug. Please fix it :)

![image](https://github.com/datguypiko/Firefox-Mod-Blur/assets/116523493/ece966b1-bbb9-49fe-a1c6-206d93fa8fe7)

**Comment by datguypiko** [comment]
That's a very interesting bug that shouldn't be affecting websites.
I fixed it. Redownload the userContent.css file or 

change at the end to this

```css
@-moz-document url("about:blank") {

/*   html:not(#ublock0-epicker),
  html:not(#ublock0-epicker) body, */
  #newtab-customize-overlay {
    background-color: var(--firefoxcss-main-bg-color) !important;
  }
}

```
