### ISSUE TITLE
[Request] Custom UI font

### ISSUE THREAD

**Issue by alixyz-1** [datguypiko/Firefox-Mod-Blur#76]
Would it be possible to either include font customisation or compatibility for adding font override in userChrome.css as below:
* { font-family: "noto sans" !important;}

Adding this causes bugs in the custom min-max-close buttons (using macos-style right-side) as well as an issue with the search bar displaying and potentially others unknown. Thanks!

**Comment by datguypiko** [comment]
Works fine for me on windows.
```css
* {
  font-family: noto sans !important;
  letter-spacing: 0.02rem !important;
}
```

![image](https://github.com/datguypiko/Firefox-Mod-Blur/assets/61329159/ef5bcbe5-00d9-427d-8d31-123a27d05496)
