### ISSUE TITLE
the forward and backward icons 

### ISSUE THREAD

**Issue by yiiyahui** [datguypiko/Firefox-Mod-Blur#79]
The forward and backward icons are too large in proportion. the default arrow icons are better.
 Can you please remove them in the next version?
![Screenshot 2023-09-01 235250](https://github.com/datguypiko/Firefox-Mod-Blur/assets/30188835/db92583f-177b-4bad-b6a1-d4553f7ad0e3)

default:
![Screenshot 2023-09-01 235032](https://github.com/datguypiko/Firefox-Mod-Blur/assets/30188835/903ff46f-5370-41fd-b3f7-9dc34a807bd2)

**Comment by datguypiko** [comment]
Remove the lines 
```css

#forward-button,
  menugroup > #context-forward,
  #search-container #searchbar .search-go-button,
  #urlbar-go-button {
    list-style-image: url(image/right-arrow.svg) !important;
  }

  #back-button,
  menugroup > #context-back {
    list-style-image: url(image/left-arrow.svg) !important;
  }

```
and
```css
#forward-button,
  menugroup > #context-forward,
  #search-container #searchbar .search-go-button,
  #urlbar-go-button {
    list-style-image: url(image/right-arrow-light.svg) !important;
  }

  #back-button,
  menugroup > #context-back {
    list-style-image: url(image/left-arrow-light.svg) !important;
  }

```
