### ISSUE TITLE
How to autohide the toolbar?

### ISSUE THREAD

**Issue by ryannmahajan** [datguypiko/Firefox-Mod-Blur#83]
Hello, I swapped the order of toolbar and tab bar so that the toolbar is at the bottom. I would like the toolbar to autohide. I tried the autohide-tab-bar mod after switching the tab-bar and toolbar names but no dice. Any idea how I can achieve this?

**Comment by datguypiko** [comment]
To hide the search bar.
```css
#nav-bar:not([customizing])  {
   visibility: collapse !important;
   transition: visibility 0ms linear 450ms !important;
  }

#navigator-toolbox:hover #nav-bar  {
    visibility: visible !important;
    transition-delay: 18ms !important;
}
```


To hide the search bar with the bookmarks bar.
```css
/* Tab hide based on https://mrotherguy.github.io/firefox-csshacks/?file=autohide_tabstoolbar.css */
#nav-bar:not([customizing])  {
   visibility: collapse !important;
   transition: visibility 0ms linear 450ms !important;
  }

#navigator-toolbox:hover #nav-bar  {
    visibility: visible !important;
    transition-delay: 18ms !important;
}

  /* Bookmarks hide */
#PersonalToolbar {
    --uc-bm-height: 24px;
    /* Might need to adjust if the toolbar has other buttons */
    --uc-bm-padding: 6px;
    /* Vertical padding to be applied to bookmarks */
    padding: 1px 6px !important;
    position: relative !important;
  }
  
  :root[uidensity="touch"] #PersonalToolbar {
    --uc-bm-padding: 6px;
  }
  
  #PersonalToolbar:not([customizing]) {
    margin-bottom: calc(
      2px - var(--uc-bm-height) - 2 * var(--uc-bm-padding)
    ) !important;
    transform: rotateX(90deg) !important;
    transform-origin: top !important;
    transition: transform 48ms linear 450ms !important;
    z-index: 2 !important;
  }
  
  #PlacesToolbarItems > .bookmark-item {
    padding-block: var(--uc-bm-padding) !important;
    padding-left: 6px !important;
    padding-right: 6px !important;
  }
  
  #PlacesToolbarItems > .bookmark-item .toolbarbutton-icon {
    transition: opacity 20ms linear 450ms !important;
    opacity: 0 !important;
  }
  
  /* Show when cursor is over the toolbar area */
  #navigator-toolbox:hover > #PersonalToolbar {
    transition-delay: 18ms !important;
    transform: rotateX(0) !important;
  }
  
  #navigator-toolbox:hover
    #PlacesToolbarItems
    > .bookmark-item
    .toolbarbutton-icon {
    transition-delay: 40ms !important;
    opacity: 1 !important;
  }
  
  #PlacesToolbarItems > .bookmark-item .toolbarbutton-text {
    transition: opacity 20ms linear 450ms !important;
    opacity: 0 !important;
  }
  
  #navigator-toolbox:hover
    #PlacesToolbarItems
    > .bookmark-item
    .toolbarbutton-text {
    transition-delay: 30ms !important;
    opacity: 1 !important;
  }



```
