### ISSUE TITLE
please make a one liner theme with this one

### ISSUE THREAD

**Issue by kb12000** [datguypiko/Firefox-Mod-Blur#86]

**Comment by qunp1** [comment]
if the compact view is what you want maybe you should try making the tabs appear on hover (thankfully there is a mod for that)

**Comment by 1111Al** [comment]
I could install blur theme on the default FF Mod blur
![FF blur left buttons](https://github.com/datguypiko/Firefox-Mod-Blur/assets/122782530/ddcbbfcb-7b46-46f7-98cc-fd2bcd720b41)

**Comment by yiiyahui** [comment]
![1](https://github.com/datguypiko/Firefox-Mod-Blur/assets/30188835/622b0b1b-35a0-4f17-9827-fad6fa05357a)

I mod a oneline version and also used the [Adaptive Tab Bar Color](https://addons.mozilla.org/en-US/firefox/addon/adaptive-tab-bar-colour/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search) extension, The following additions or modifications are needed. Looking forward to the author releasing a new version.

**Do not modify the colors if the Adaptive Tab Bar Color extension is not used.**

Edit(work with  Adaptive Tab Bar Color)
``` css
    --firefoxcss-new-tab-button-active: color-mix(in srgb, currentColor 10%, transparent);
    --firefoxcss-new-tab-button-hover: color-mix(in srgb, currentColor 15%, transparent);
	
	/*================= G L O B A L   V A R I A B L E S ====================*/
:root {
  --firefoxcss-border-radius: 6px;
  --firefoxcss-control-buttons-margin: 100px;
  --firefoxcss-tab-min-width: 100px;
  --firefoxcss-tab-max-width: 150px;
}
``` 
**Add or Remove.**
``` css
#back-button[disabled="true"],#forward-button[disabled="true"]{display: none !important;}
/*===================== T O O L B A R   O R D E R ========================*/
@media (min-width: 850px) {
  #navigator-toolbox {
    display: flex !important; 
    justify-content: start !important; 
    flex-wrap: wrap !important;
    flex-direction: row !important;                                
  }
  #navigator-toolbox > #titlebar {
    -moz-appearance: unset !important; 
    margin-left: 1px !important; 
    flex: 1 !important; 
  }
  Order of Toolbars
    * 0 - top
    * 1 - second from top
    * 2 - bottom */
  #navigator-toolbox #nav-bar {
    order: 0 !important;
  }
  #titlebar {
    order: 1 !important;
    -moz-appearance: unset !important; 
    margin-left: 1px !important; 
    flex: 1 !important; 
  }
  #PersonalToolbar {
    order: 2 !important;
    width: 100%;
  }
  #tab-notification-deck {
    order: 3; 
    width: 100%;
}
/* Extra titlebar menu (above or below tabs, opens with alt) */
  #titlebar #toolbar-menubar {
    order: 0 !important;
  }
  #nav-bar > #nav-bar-customization-target > #urlbar-container {
    width: 325px !important;
    transition: width 500ms !important;
  }
  #nav-bar > #nav-bar-customization-target  > #urlbar-container:hover:focus-within {
    width:  425px !important;
    transition: width 500ms !important;
  }
}

#navigator-toolbox {
  padding-top: 3px !important;
  padding-bottom: 4px !important;
}

/*===================== H E I G H T   F I X E S ===========================*/
/* Search Bar height */ 
#urlbar-container {
  --urlbar-container-height: 38px !important;
}

#urlbar-container #urlbar {
  --urlbar-toolbar-height: 38px !important;
  --urlbar-height: 28px !important;
}
.urlbarView-results> .urlbarView-row > .urlbarView-row-inner > .urlbarView-no-wrap {
  max-width: 40% !important;
  flex-basis: auto;
}

/*========================= S E A R C H   B A R =========================*/
#urlbar .urlbar-input-box {
  text-align: left;
}
#urlbar {
  --autocomplete-popup-highlight-background: var(
    --firefoxcss-url-autocomplete-highlight
  ) !important;
  border: 0 !important;
  background-color: color-mix(in srgb, currentColor 8%, transparent) !important;
  margin-top: 1px !important;
}
/* Styling Extra search bar that you can add to firefox */
#search-container #searchbar {
  outline: 0 !important;
  border: 0 !important;
  border-radius: var(--firefoxcss-border-radius) !important;
  background-color: color-mix(in srgb, currentColor 8%, transparent) !important;
}

/*=========================== T A B S ================================*/
/* Non active tabs have darker text */
.tabbrowser-tab:not([selected]):not([multiselected]):not(:hover) .tab-label-container .tab-label {
  color: var(--toolbox-non-lwt-textcolor) !important;
}
/* Main BAR */
#navigator-toolbox {
  --tabs-border-color: none !important;
  --tabs-navbar-shadow-size: 0px !important;
  background-color: var(--firefoxcss-main-bg-color) !important;
}
#tabbrowser-tabs {
  --tab-loading-fill: transparent !important;
  margin-left: -4px !important;
}

/* Width of the tabs. Important to have Fadein or it breaks fonctionality */
/* not([style^="max-width"] :not([overflow])*/
#tabbrowser-tabs .tabbrowser-tab[fadein]:not([pinned]) {
  max-width: var(--firefoxcss-tab-max-width) !important;
  min-width: var(--firefoxcss-tab-min-width) !important;
  margin-left: 6px !important;
}

/* Selected tabs width increase */
#tabbrowser-tabs:not([overflow])
  .tabbrowser-tab[selected][fadein]:not([pinned]) {
  max-width: 200px !important;
  min-width: 200px !important;
}

/* Normal tabs design */
.tabbrowser-tab .tab-background:not([selected]) {
  border: 0 !important;
  border-radius: var(--firefoxcss-border-radius) !important;
  background-image: none !important;
  background-color: color-mix(in srgb, currentColor 8%, transparent) !important;
  transition: background-color 250ms ease !important;
  box-shadow: none !important;
  }
  
  /* Normal tabs design on hover */
#tabbrowser-tabs .tabbrowser-tab:hover > .tab-stack > .tab-background:not([selected]) {
  border: 0 !important;
  border-radius: var(--firefoxcss-border-radius) !important;
  background-image: none !important;
  background-color: color-mix(in srgb, currentColor 15%, transparent) !important;
  box-shadow: none !important;
}

#tabbrowser-tabs
  .tabbrowser-tab
  .tab-background:is([selected]):is([multiselected]) {
  outline: none !important;
  }
 
  .browserContainer > findbar .findbar-textbox {
  background-color: color-mix(in srgb, currentColor 8%, transparent) !important;
}

#screenshotsPagePanel {top: 50px;}

/* ------------------------- Move find bar ------------------------ */
 findbar {
  position: absolute;
  top: -5px;
  right: 0px;
  contain: content;
  border-radius: 0 0 var(--toolbarbutton-border-radius) var(--toolbarbutton-border-radius);
  border-top: none !important;
}
.findbar-find-status, findbar .checkbox-check,.findbar-highlight,
.findbar-case-sensitive, .findbar-match-diacritics, .findbar-entire-word {
  display: none;
}
.findbar-closebutton {transform: scale(0.8);}
findbar:not([pinned]):hover .findbar-closebutton {
  opacity: 1;
  visibility: visible !important;
  transform: scale(0.8);
  border-radius: 100% !important;
  transition: opacity 0.25s ease, visibility 0.25s ease, background-color 0.15s ease !important;
}
```
