### ISSUE TITLE
For macos version

### ISSUE THREAD

**Issue by yiiyahui** [datguypiko/Firefox-Mod-Blur#87]
```css
/*===========================================================*/
#nav-bar {padding-left: 64px;}

#navigator-toolbox:not([inFullscreen]) #TabsToolbar .titlebar-buttonbox-container {
  visibility: visible !important;
  position: absolute !important;
  top: 12px;
}
```

![Screen Shot 2023-10-16 at 10 17 56 PM](https://github.com/datguypiko/Firefox-Mod-Blur/assets/30188835/a59cf0ea-cd30-49e2-97bb-eba92f712f33)
