### ISSUE TITLE
Single-line Pocket recommendations cause problems

### ISSUE THREAD

**Issue by realmalikov** [datguypiko/Firefox-Mod-Blur#92]
When I opened Firefox with this theme for the first time, I immediately noticed that the countless Pocket articles take up too much space on the homepage (and also don't match the rest of the look).

So I wanted to reduce the pocket recommendations to one line, but realized that this is no longer possible by default. After a quick reddit search, I found out that this can be changed in `about:config` by setting `browser.newtabpage.activity-stream.discoverystream.enabled` to `false`.

Now I have one-line recommendations and fortunately the colors of the cards have adapted to the rest, but unfortunately I have encountered two problems:

1. Any text in the recommendation card is underlined in white.
2. The search bar adapts to the larger overall width of the cards, but the shortcuts don't, they are even moved slightly, if I'm not mistaken.

Here is a before/after comparison to visualize this:
![firefox](https://github.com/datguypiko/Firefox-Mod-Blur/assets/126217872/28a970b8-f36f-43d6-96a7-23e59222ddf0)

**Comment by datguypiko** [comment]
I have never used it. How do I enable it?
![image](https://github.com/datguypiko/Firefox-Mod-Blur/assets/61329159/0a1982dd-16b7-4048-8895-31f829cfa56d)
![image](https://github.com/datguypiko/Firefox-Mod-Blur/assets/61329159/85a27024-2f1e-4e96-8a67-ce29067d5718)

**Comment by realmalikov** [comment]
[This article might be helpful](https://support.mozilla.org/en-US/kb/view-articles-recommended-pocket-firefox-new-tab-homepage).

You may be in one of the many regions that is not yet supported.
> Recommended by Pocket stories on the [New Tab page](https://support.mozilla.org/en-US/kb/about-new-tab-page) is a feature currently available in the U.S., Canada, the U.K., Germany, Italy, France and Spain. We're working to bring it to other countries.

Perhaps it will work if you change your region or use the method described in the article.

**Comment by datguypiko** [comment]
here add this code in userContent.css file at line around 491.

```css
.section-list .card-outer > a {
    text-decoration: none !important
}

.collapsible-section .top-sites-list {
    display: flex !important;
    justify-content: center !important;
    align-items: center !important;
    align-content: space-around !important;
    flex-direction: row !important;
    flex-wrap: wrap !important;
}

.collapsible-section .sections-list .section-list {
  justify-content: center !important
}

```

**Comment by realmalikov** [comment]
Nice, thank you for your quick help!

![grafik](https://github.com/datguypiko/Firefox-Mod-Blur/assets/126217872/00d7b2b7-f8a9-49c3-bc26-2862fcd38d41)

**Comment by realmalikov** [comment]
Card fix for smaller screens:

```css
.sections-list .section-list {
  grid-template-columns: repeat(auto-fit, minmax(192px, 1fr)) !important;  /* added 1fr */ 
}
```
