### ISSUE TITLE
Is it possible to remove the black line under the tab bar?

### ISSUE THREAD

**Issue by Anastasis-M** [datguypiko/Firefox-Mod-Blur#93]
![image](https://github.com/datguypiko/Firefox-Mod-Blur/assets/77619714/17aa9729-36c8-4d0b-ad4b-b53fe109e9f3)
It wasn't there in the previous versions. Maybe its my fault cause I've made some modifications (but mainly color stuff), if it's not supposed to be there could you share the code that removes it?

**Comment by datguypiko** [comment]
If you use "spill-style-part1-file.css" file update it or add this code to userchrome.css file.

```css
#main-window #navigator-toolbox {
    border-bottom: none !important;
}
```
