### ISSUE TITLE
[Ques]: Removing the close button and shifting extensions to right

### ISSUE THREAD

**Issue by niksingh710** [datguypiko/Firefox-Mod-Blur#94]
![image](https://github.com/datguypiko/Firefox-Mod-Blur/assets/60490474/68e90a29-c26c-4334-8bd9-a4c67b23bf46)
How can i remove the close button and shift the extensions to extreme right?

**Comment by datguypiko** [comment]
Lower `--firefoxcss-control-buttons-margin` value in userChrome.css file (225 line).

To hide close button 
```css 
.titlebar-buttonbox-container .titlebar-button.titlebar-close{
    display: none !important;
}
```

**Comment by niksingh710** [comment]
> Lower `--firefoxcss-control-buttons-margin` value in userChrome.css file (225 line).
> 
> To hide close button
> 
> ```css
> .titlebar-buttonbox-container .titlebar-button.titlebar-close{
>     display: none !important;
> }
> ```

Thanks able to remove the button but yet the spacing between the window border and extension is there.

![image](https://github.com/datguypiko/Firefox-Mod-Blur/assets/60490474/a3eeeb9b-4db3-4862-8656-f0b005fca17c)

**Comment by datguypiko** [comment]
Here is fedora example, works perfectly fine after lowering the value.

before: 
![image](https://github.com/datguypiko/Firefox-Mod-Blur/assets/61329159/bbda0253-b641-44ac-b804-bf6e97bf26fd)

after: `--firefoxcss-control-buttons-margin: 0px;`
![image](https://github.com/datguypiko/Firefox-Mod-Blur/assets/61329159/03d7ab6d-55f5-4ecc-b88e-1482f8055845)

**Comment by niksingh710** [comment]
seems like m missing something as this is not working for me.
and i don't see any other variable modifying the padding.
I will close this for now and if i got the root cause of the issue will comment.

**Comment by niksingh710** [comment]
```css

  #navigator-toolbox #nav-bar {
    padding-right: initial !important;
  }

```

adding this moves the extension to right.
