### ISSUE TITLE
Feature request - Tabs count

### ISSUE THREAD

**Issue by qunp1** [datguypiko/Firefox-Mod-Blur#96]
is it possible to move the 'all tabs button' from tabs bar to navbar above so the number of current open tabs can be visible when tabs are hidden. (or anything else to show the current nbr of tabs).
![image](https://github.com/datguypiko/Firefox-Mod-Blur/assets/150928288/3b4e039b-5b61-4205-8366-5c17198f1d10)

**Comment by datguypiko** [comment]
You can do it two ways. 
1. Simple is just using this [extension ](https://addons.mozilla.org/en-GB/firefox/addon/tab-list-button-enhanced/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search). Then right clicking on it in extension menu and "pin to toolbar". In customization view you can move it anywhere you want. 
![image](https://github.com/datguypiko/Firefox-Mod-Blur/assets/61329159/a775eb94-ee18-4e3f-84c4-48ff0fb7cc30)
2. Using This code, but you will need to specify position with "left: 100px;" where you want it to stay.
 ![image](https://github.com/datguypiko/Firefox-Mod-Blur/assets/61329159/f319714d-08e8-4302-a949-7fa86ba3eb88)
```css
#TabsToolbar-customization-target {  
    counter-reset: tabCount;  
}  
.tabbrowser-tab {  
    counter-increment: tabCount;  
}  
#alltabs-button > .toolbarbutton-badge-stack > .toolbarbutton-icon {  
    visibility: collapse !important;  
}  
#alltabs-button > .toolbarbutton-badge-stack {  
    position: relative !important;  
}  

#alltabs-button {
    position: absolute !important;  
    top: 5px;
    left: 100px;
}
#alltabs-button > .toolbarbutton-badge-stack::before {  
    content: counter(tabCount);  
    border-bottom: 1px solid var(--toolbarbutton-icon-fill);  
    color: var(--toolbarbutton-icon-fill);  
    opacity: var(--toolbarbutton-icon-fill-opacity);  
    position: absolute;  
    bottom: var(--toolbarbutton-inner-padding);  
    left: 50%;  
    transform: translateX(-50%);  
    padding: 0 3px;  
}
```

**Comment by qunp1** [comment]
thank you, the code works but it doesn't show until i hover on toolbar, i need it to stay visible

**Comment by datguypiko** [comment]
Here add this at the end of the file, should work when tabs bar are hidden
```css
#alltabs-button {
    visibility: visible !important;
}
```
